  # docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
    - 8080:8080
    - 50000:50000
    container_name: jenkins
    volumes:
      - /Users/eric/Repos/docker-jenkins-tiny/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  cypress:
    image: cypress/included:latest
    entrypoint: bash -c ./${DOCKER_DIR}/entrypoint.sh